"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { parseTeamPaste } from "@/utils/teamParser";
import { type Team } from "@/types/team";
import { TeamCard } from "@/components/TeamCard";
import Link from "next/link";

const GENERATIONS = [
  "Gen 1",
  "Gen 2",
  "Gen 3",
  "Gen 4",
  "Gen 5",
  "Gen 6",
  "Gen 7",
  "Gen 8",
  "Gen 9",
];

const FORMATS = [
  "OU",
  "UU",
  "RU",
  "NU",
  "PU",
  "Ubers",
  "Doubles OU",
];

interface SuggestedTeam {
  teamPaste: string;
  description: string;
  generation: string;
  format: string;
  strategy: string;
}

export default function SuggestionsPage() {
  const router = useRouter();
  const [generation, setGeneration] = useState("Gen 9");
  const [format, setFormat] = useState("OU");
  const [strategy, setStrategy] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [suggestedTeam, setSuggestedTeam] = useState<SuggestedTeam | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [rateLimitInfo, setRateLimitInfo] = useState<{ remaining: number; limit: number } | null>(null);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);
    setSuggestedTeam(null);

    try {
      const response = await fetch("/api/ai/suggest-team", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          generation,
          format,
          strategy: strategy || undefined,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        // Handle rate limit errors with detailed message
        if (response.status === 429) {
          const details = data.details || data.error || "Rate limit exceeded. Please try again later.";
          throw new Error(details);
        }
        throw new Error(data.error || "Failed to generate team suggestion");
      }

      // Capture rate limit info from headers
      const remaining = response.headers.get("X-RateLimit-Remaining");
      const limit = response.headers.get("X-RateLimit-Limit");
      if (remaining && limit) {
        setRateLimitInfo({ remaining: parseInt(remaining), limit: parseInt(limit) });
      }

      setSuggestedTeam(data);
    } catch (err) {
      console.error("Error generating team:", err);
      setError(err instanceof Error ? err.message : "Failed to generate team suggestion");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async () => {
    if (!suggestedTeam) return;

    setIsSaving(true);
    setError(null);

    try {
      // Parse the team to extract Pokemon names for Key Pokemon field
      const parsed = parseTeamPaste(suggestedTeam.teamPaste);
      const keyPokemon = parsed.pokemon.map((p) => p.name);

      const team: Team = {
        teamName: `AI Suggested - ${generation} ${format}`,
        teamPaste: suggestedTeam.teamPaste,
        format: format,
        generation: generation,
        strategy: suggestedTeam.description || suggestedTeam.strategy,
        keyPokemon: keyPokemon.length > 0 ? keyPokemon : undefined,
      };

      const response = await fetch("/api/teams", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(team),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to save team");
      }

      // Redirect to home page after successful save
      router.push("/");
    } catch (err) {
      console.error("Error saving team:", err);
      setError(err instanceof Error ? err.message : "Failed to save team");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <main className="min-h-screen bg-[var(--notion-gray)] py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <div className="flex items-center gap-4 mb-4">
            <Link
              href="/"
              className="text-[var(--notion-blue)] hover:underline opacity-80 hover:opacity-100"
            >
              ← Back to Teams
            </Link>
          </div>
          <h1 className="text-[40px] font-bold text-[var(--foreground)] mb-2 leading-tight">
            AI Team Suggestions
          </h1>
          <p className="text-[16px] text-[var(--foreground)] opacity-70">
            Get optimal Pokemon Showdown teams generated by AI based on usage stats
          </p>
        </div>

        <div className="bg-white dark:bg-[#191919] border border-[var(--notion-border)] rounded-[3px] p-6 mb-6">
          <div className="space-y-4">
            <div>
              <label className="block text-[14px] font-medium text-[var(--foreground)] mb-2 opacity-80">
                Generation
              </label>
              <select
                value={generation}
                onChange={(e) => setGeneration(e.target.value)}
                className="w-full px-3 py-2 bg-[var(--notion-gray)] border border-[var(--notion-border)] rounded text-[14px] text-[var(--foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--notion-blue)]"
              >
                {GENERATIONS.map((gen) => (
                  <option key={gen} value={gen}>
                    {gen}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-[14px] font-medium text-[var(--foreground)] mb-2 opacity-80">
                Format
              </label>
              <select
                value={format}
                onChange={(e) => setFormat(e.target.value)}
                className="w-full px-3 py-2 bg-[var(--notion-gray)] border border-[var(--notion-border)] rounded text-[14px] text-[var(--foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--notion-blue)]"
              >
                {FORMATS.map((fmt) => (
                  <option key={fmt} value={fmt}>
                    {fmt}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-[14px] font-medium text-[var(--foreground)] mb-2 opacity-80">
                Strategy (Optional)
              </label>
              <textarea
                value={strategy}
                onChange={(e) => setStrategy(e.target.value)}
                placeholder="e.g., Hyper offense, Stall, Balance, Weather team..."
                className="w-full px-3 py-2 bg-[var(--notion-gray)] border border-[var(--notion-border)] rounded text-[14px] text-[var(--foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--notion-blue)] min-h-[80px] resize-y"
              />
            </div>

            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="w-full px-4 py-2 bg-[var(--notion-blue)] text-white rounded text-[14px] font-medium hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isGenerating ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  Generating Team...
                </span>
              ) : (
                "Generate Team"
              )}
            </button>

            {rateLimitInfo && (
              <div className="text-[12px] text-[var(--foreground)] opacity-60 text-center">
                {rateLimitInfo.remaining} of {rateLimitInfo.limit} requests remaining this hour
              </div>
            )}
          </div>
        </div>

        {error && (
          <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-[3px] p-4 mb-6">
            <p className="text-[14px] text-red-600 dark:text-red-400">{error}</p>
          </div>
        )}

        {suggestedTeam && (() => {
          // Convert suggestedTeam to Team format for TeamCard
          const parsed = parseTeamPaste(suggestedTeam.teamPaste);
          const keyPokemon = parsed.pokemon.map((p) => p.name);
          
          const teamForCard: Team = {
            teamName: `AI Suggested - ${generation} ${format}`,
            teamPaste: suggestedTeam.teamPaste,
            format: format,
            generation: generation,
            strategy: suggestedTeam.description || suggestedTeam.strategy,
            keyPokemon: keyPokemon.length > 0 ? keyPokemon : undefined,
          };

          return (
            <div className="space-y-4">
              <TeamCard team={teamForCard} />
              
              <div className="flex flex-row items-center justify-center gap-3">
                <button
                  onClick={handleSave}
                  disabled={isSaving}
                  className="px-4 py-2 bg-[var(--notion-blue)] text-white rounded text-[14px] font-medium hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                >
                  {isSaving ? (
                    <>
                      <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      Saving...
                    </>
                  ) : (
                    "Save to Notion"
                  )}
                </button>
                <button
                  onClick={handleGenerate}
                  disabled={isGenerating}
                  className="px-4 py-2 bg-[var(--notion-gray)] border border-[var(--notion-border)] text-[var(--foreground)] rounded text-[14px] font-medium hover:bg-[var(--notion-hover)] transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                >
                  {isGenerating ? (
                    <>
                      <span className="w-4 h-4 border-2 border-[var(--foreground)] border-t-transparent rounded-full animate-spin" />
                      Generating...
                    </>
                  ) : (
                    "Generate Another"
                  )}
                </button>
              </div>
            </div>
          );
        })()}
      </div>
    </main>
  );
}

